DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS PRODUCT_CTGR;
  
CREATE TABLE BRAND (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

  
CREATE TABLE COLOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

  
CREATE TABLE PRODUCT_CTGR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

  
CREATE TABLE PRODUCT(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  QUANTITY INT NOT NULL,
  SIZE VARCHAR(5) NOT NULL,
  PRICE INT NOT NULL,
  BRAND_ID INT NOT NULL,
  foreign key (BRAND_ID) references BRAND(ID),
  COLOR_ID INT NOT NULL,
  foreign key (COLOR_ID) references COLOR(ID),
  PRODUCT_CTGR_ID INT NOT NULL,
  foreign key (PRODUCT_CTGR_ID) references PRODUCT_CTGR(ID)
);